live_config_reload = true
import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new -As Alacritty"]

[window]
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Fullscreen"

[font]
size = 13.80
# offset = { x = 1 }
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
bold = { family = "SpaceMono Nerd Font", style = "Bold" }
italic = { family = "SpaceMono Nerd Font", style = "Italic" }
bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[selection]
save_to_clipboard = true
